<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240422103651" tests="1" file="unittest/loader.py" time="0.010" timestamp="2024-04-22T10:36:51" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest.ats" name="tests" time="0.010" timestamp="2024-04-22T10:36:51" file="/usr/lib/python3.10/unittest/loader.py" line="33">
		<error type="ImportError" message="Failed to import test module: ats.tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.10/unittest/loader.py&quot;, line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;/usr/lib/python3.10/unittest/loader.py&quot;, line 377, in _get_module_from_name
    __import__(name)
  File &quot;/home/burhanuddin/server/server/ats/tests.py&quot;, line 1, in &lt;module&gt;
    import models
ModuleNotFoundError: No module named 'models'
"><![CDATA[ImportError: Failed to import test module: ats.tests
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/burhanuddin/server/server/ats/tests.py", line 1, in <module>
    import models
ModuleNotFoundError: No module named 'models'

]]></error>
	</testcase>
</testsuite>
